<h3 style="background-color: #0066CC; color:white"><br>SYARAT DAN JADWAL PENDAFTARAN PPDB JAWA TENGAH TAHUN 2020 </br></br></h3>
<img src="image/berita.JPG" style="float:left; margin-left: 10px;"><br>
<p style="text-align:justify; margin:5px 10px 5px 10px; float:left; padding-left:0.8em"> 
    SEMARANG, KOMPAS.com ? Pandemi Covid-19 juga berimbas pada pelaksanaan Penerimaan Peserta Didik Baru ( PPDB) yang bakal digelar pada Juni 2020. Kepala Dinas Pendidikan dan Kebudayaan Jawa Tengah Jumeri mengatakan PPDB pada tahun ini berbeda dari tahun sebelumnya. Syarat pendaftaran saat ini tak lagi mengacu pada surat keterangan ujian nasional (UN) akan tetapi berdasarkan nilai rapor dari semester satu sampai lima. ?Kalau dulu syarat mendaftar acuannya surat keterangan UN, sekarang karena UN ditiadakan maka acuannya adalah nilai raport dari semester 1-5. Kami sudah berikan perintahkan Kepala Sekolah Menengah Pertama ( SMP) Negeri dan Swasta serta Mts untuk membuat surat keterangan nilai rapor itu,? kata Jumeri dalam keterangan tertulis, Jumat (8/5/2020).
<br><br>Selain itu, terkait zonasi ada perbedaan dari tahun lalu. Jika tahun lalu jalur zonasi ditetapkan 80 persen, pada pelaksanaan PPDB tahun ini, zonasi hanya ditetapkan minimal 50 persen. Sisanya diisi jalur prestasi 30 persen, afirmasi untuk anak miskin, difabel dan olahraga sebesar 15 persen dan jalur perpindahan orang tua sebesar 5 persen. Jumeri menjelaskan, untuk pelaksanaan pendaftaran jalur inklusi dan kelas olahraga akan dimulai pada 2-4 Juni 2020, sedangkan jalur reguler dimulai pada 15-25 Juni 2020. ?Semua pelaksanaan pendaftaran akan dilaksanakan secara online. Siswa dan orang tua siswa diminta tidak perlu datang ke sekolah untuk melakukan pendaftaran,? ujarnya. Bahkan, sejumlah persyaratan, lanjut dia, juga akan diubah sesuai kondisi. Misalnya surat keterangan sehat dari dokter untuk calon siswa SMK, karena Covid-19, surat itu diganti dengan pernyataan orangtua.
<br><br>?Soalnya kalau harus mencari surat itu, nanti mereka berbondong-bondong ke rumah sakit atau puskesmas. Itu cukup berbahaya, sehingga kami mengganti dengan keterangan orangtua,? jelasnya. Baca juga: Banyak Mendadak Miskin, SKTM (Akhirnya) Dihapus di PPDB 2019 Terkait daya tampung, PPDB tahun ini menampung 216.156 siswa, terdiri dari kapasitas SMA 115.908 dan kapasitas SMK 100.248. Sementara lulusan SMP/Mts tahun ini di Jateng totalnya sekitar 513.178 siswa. ?Kami tidak menambah kuota, karena sisa kuota ini biar ditangkap sekolah-sekolah swasta yang ada,? tegasnya.
<br><br>Sementara itu, Gubernur Jawa Tengah Ganjar Pranowo mengingatkan agar orangtua siswa tidak memalsukan data-data demi anaknya untuk diterima di sekolah tertentu. Ganjar juga mengusulkan kepada Dinas Pendidikan untuk memberikan jalur khusus bagi anak-anak tenaga medis yang berjuang melawan Covid-19. Anak-anak para tenaga medis itu diminta Ganjar dimasukkan dalam kuota jalur afirmasi. ?Jadi ini usul saja, sebagai bentuk apresiasi dan penghargaan kepada para tenaga kesehatan yang telah berjuang melawan Covid-19,? katanya
<br><br>Artikel ini telah tayang di Kompas.com dengan judul ?Catat, Ini Syarat dan Jadwal Pendaftaran PPDB Jawa Tengah Tahun 2020?, https://regional.kompas.com/read/2020/05/08/17410401/catat-ini-syarat-dan-jadwal-pendaftaran-ppdb-jawa-tengah-tahun-2020.
<br><br>Penulis : Kontributor Semarang, Riska Farasonalia
<br><br>Editor : Khairina
</p>
<br><br><br><br><br><br><br>